version: "3"
services:
  app:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3005:3001"
    volumes:
      - .:/usr/root/whatsapp-messaging-service:cached
